import './globals.css'
// import store from './store'
// import { Provider } from 'react-redux'
import ReduxProvider from './store/provider'
// import { Inter } from 'next/font/google'

// const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  // title: 'Create Next App',
  title: 'First lesson',
  // description: 'Generated by create next app',
  description: 'Lern next JS and react with decode',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        {/* <Provider store={store}>
          {children}
        </Provider> */}
        <ReduxProvider>
          {children}
        </ReduxProvider>
      </body>
      {/* <body className={inter.className}>{children}</body> */}
    </html>
  )
}
